'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5466
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Saboteur.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property AccionFarolRoto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AccionFarolRoto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AccionFarolRotoOpaco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AccionFarolRotoOpaco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AccionPicoRoto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AccionPicoRoto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AccionPicoRotoOpaco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AccionPicoRotoOpaco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AccionVagonRoto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AccionVagonRoto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AccionVagonRotoOpaco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AccionVagonRotoOpaco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property card_back_side() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("card back side", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mapa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mapa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ReparadoFarol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReparadoFarol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ReparadoFarolVagon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReparadoFarolVagon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ReparadoPico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReparadoPico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ReparadoPicoFarol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReparadoPicoFarol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ReparadoPicoVagon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReparadoPicoVagon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ReparadoVagon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReparadoVagon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RotoFarol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RotoFarol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RotoPico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RotoPico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RotoVagon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RotoVagon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tunel3H() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tunel3H", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tunel3V() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tunel3V", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tunel4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tunel4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TunelBloqueado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TunelBloqueado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TunelCortado3H() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TunelCortado3H", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TunelCortado3V() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TunelCortado3V", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TunelCortado4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TunelCortado4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TunelCortadoDerecha() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TunelCortadoDerecha", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TunelCortadoH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TunelCortadoH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TunelCortadoInterrogante() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TunelCortadoInterrogante", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TunelCortadoLDerecha() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TunelCortadoLDerecha", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TunelCortadoLIzquierda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TunelCortadoLIzquierda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TunelCortadoV() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TunelCortadoV", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TunelHorizontal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TunelHorizontal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TunelLDerecha() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TunelLDerecha", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TunelLIzquierda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TunelLIzquierda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TunelVertical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TunelVertical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
